#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

if [[ ! $(pgrep -u $USER "\bstartplasma-x11$") ]]; then {
	setbg &                                              # set the background with the `setbg` script
	xcompmgr -c &                                        # xcompmgr for transparency
	dunst &                                              # dunst for notifications
	synclient TouchpadOff=1 &                            # Disable touchpad
}
fi
mpd &                                                    # music player daemon-you might prefer it as a service though
xset r rate 300 50 &                                     # Speed xrate up
xset -b &                                                # Removes annoying bell
unclutter &                                              # Remove mouse when idle
xmodmap $DOT/Xmodmap &                                   # Swaps capslock and esc, enables pgup/pgdown near arrow keys
xrdb ${DOT_CONFIG_HOME:-$HOME/.config}/x11/xresources &  # Uncomment to use Xresources colors/settings on startup


#spotifyd &
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info
#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.

# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
#pidof -s runit &&
	#! pidof -s pulseaudio >/dev/null 2>&1 &&
	#setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
#[ -n "$xrdbpid" ] && wait "$xrdbpid"
